version: '3.7'
services:
    postgres:
        image: postgres:10.5-alpine
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        networks:
          - private
        volumes:
          - ./data:/var/lib/postgresql/data
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - private
    api:
      build: api/
      restart: always
      ports:
        - '3000:3000'
      networks:
        - private
      depends_on:
        - postgres

networks:
  private: