version: '3.7'
services:
    postgres:
        image: postgres:latest
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
          - LANG=en_US.utf8 
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        networks:
          - private
        volumes:
          - ./data:/var/lib/postgresql/data
    adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8080
      networks:
        - private
      depends_on:
        - postgres
    api:
      build: api/
      restart: always
      ports:
        - '3000:3000'
      networks:
        - private
      depends_on:
        - postgres
    # react:
    #   build: react/
    #   restart: always
    #   ports:
    #     - '8080:3000'
    #   networks:
    #     - private
    #   depends_on:
    #     - api
networks:
  private: